version: '3'

services:
  postgresql_svc:
    container_name: kursach_db
    image: postgres:14.0
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432/tcp
    volumes:
      - ~/.kursach/pgdata:/var/lib/postgresql/data
      - ./scripts/init_postgresql.sh:/docker-entrypoint-initdb.d/init_postgresql.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
